#!/usr/bin/env ruby

require 'sinatra'
require 'faraday'

set(:traps, false)
set(:port, ENV['SINATRA_PORT'] || 80)
set(:bind, ENV['SINATRA_BIND'] || '0.0.0.0')

get('/pid') do
  Process.pid.to_s
end

get('/quit') do
  Sinatra::Application.quit!
end

get('/abort') do
  Process.kill('SEGV', Process.pid)
end

top_binding = binding

ARGV.each do |snippet|
  eval(snippet, top_binding)
end
